<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dexter_hardware</name>
  <version>0.0.1</version>
  <description>Hardware control node for Dexter robot using MKS Servo drivers via CAN</description>
  <maintainer email="seantsai06@gmail.com">sean</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>rclcpp</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>diagnostic_msgs</depend>
  <depend>dexter_hardware_interfaces</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>action_msgs</test_depend>
  <test_depend>control_msgs</test_depend>
  <test_depend>trajectory_msgs</test_depend>
  <test_depend>controller_manager</test_depend>
  <test_depend>controller_manager_msgs</test_depend>
  <test_depend>joint_trajectory_controller</test_depend>
  <test_depend>robot_state_publisher</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <hardware_interface plugin="${prefix}/dexter_hardware_plugins.xml"/>
  </export>
</package>
