"""CAN Bus Settings and Configuration"""

# CAN Message IDs (based on MKS Servo protocol)
CAN_CMD_MOTOR_ENABLE = 0x01
CAN_CMD_MOTOR_DISABLE = 0x02
CAN_CMD_MOTOR_RESET = 0x03
CAN_CMD_MOTOR_ABSOLUTE_MOVE = 0x04
CAN_CMD_MOTOR_RELATIVE_MOVE = 0x05
CAN_CMD_MOTOR_VELOCITY_MOVE = 0x06
CAN_CMD_MOTOR_STOP = 0x07
CAN_CMD_MOTOR_HOME = 0x08
CAN_CMD_MOTOR_CALIBRATE = 0x09
CAN_CMD_MOTOR_GET_STATUS = 0x0A
CAN_CMD_MOTOR_GET_POSITION = 0x0B
CAN_CMD_MOTOR_GET_TEMPERATURE = 0x0C

# Control Modes
CONTROL_MODE_ABSOLUTE = 0x00
CONTROL_MODE_RELATIVE = 0x01
CONTROL_MODE_VELOCITY = 0x02

# Default parameters
DEFAULT_CAN_BITRATE = 1000000  # 1 Mbps
DEFAULT_CAN_INTERFACE = 'can0'

# Motor parameter ranges
MOTOR_ID_MIN = 0
MOTOR_ID_MAX = 255
POSITION_MIN = -8388607  # -2^23 + 1
POSITION_MAX = 8388607   # 2^23 - 1
SPEED_MIN = 0
SPEED_MAX = 3000  # RPM
ACCELERATION_MIN = 0
ACCELERATION_MAX = 255

# Pulse-related constants
PULSES_PER_REVOLUTION = 10000
DEGREES_PER_REVOLUTION = 360.0
