schema_version: "1.0"
show:
  id: robot_show
  name: fira_show
  version: 1
  requirements:
    # These are trusted assumptions, not sensor readings.
    rail1_initial_state: TOP
    rail2_initial_state: TOP
  defaults:
    on_failure: abort_show
    command_timeout_s: 30.0
  root:
    id: show_root
    type: sequence
    children:

      - id: screen_ANGRY
        type: action
        target: screen
        command: face
        args:
          face_type: ANGRY
        timeout_s: 2.0
      
      - id: rail1_down
        type: action
        target: rail1
        command: move
        args: {steps: 16000, direction: low}
        timeout_s: 10.0

      - id: screen_default
        type: action
        target: screen
        command: face
        args:
          face_type: DEFAULT
        timeout_s: 2.0

      - id: rail1_up
        type: action
        target: rail1
        command: move
        args: {steps: 16000, direction: high}
        timeout_s: 10.0

      - id: arm_move1
        type: action
        target: arm
        command: joint_move
        args:
          positions: [0.0, 0.0, 0.0, 0.0, 0.0, -1.0]
          speed_scaling: 0.7
        timeout_s: 25.0

      - id: arm_move2
        type: action
        target: arm
        command: joint_move
        args:
          positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          speed_scaling: 0.7
        timeout_s: 25.0
